#!/bin/bash

set -o errexit

function usage() {
	echo "Usage: `basename "$0"` <uart rx pin> <uart tx pin>"
	exit 1
}

if [ "$#" -ne 2 ]; then
	usage
fi

UART_RX_PIN=$1
UART_TX_PIN=$2

echo "Skycharge UART configuration $UART_RX_PIN and $UART_TX_PIN"
config-pin $UART_RX_PIN uart
config-pin $UART_TX_PIN uart
